routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CashierController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LogActivityController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductPriceController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\PurchaseImageController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReturnProductController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransactionController;

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login'])->name('login.store');
Route::post('logout', [LoginController::class, 'logout'])->middleware('auth:admin,owner,cashier')->name('logout');
    
Route::group(['middleware' => 'auth:admin,owner,cashier'], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('home');

    Route::resource('category', CategoryController::class)->except(['edit','create']);

    Route::resource('product', ProductController::class)->except(['edit']);
    Route::get('product-others', [ProductController::class, 'others'])->name('product.others');
    Route::post('product-import', [ProductController::class, 'import'])->name('product.import');
    Route::resource('product-price', ProductPriceController::class)->only(['store', 'destroy']);
    
    Route::resource('sale', SaleController::class)->except(['edit']);
    Route::resource('transaction', TransactionController::class)->except(['index','edit']);
    Route::get('sale-trash', [SaleController::class, 'trash'])->name('sale.trash');
    
    Route::resource('purchase', PurchaseController::class)->except(['edit']);
    Route::resource('purchase-image', PurchaseImageController::class)->only(['store', 'destroy']);
    
    Route::resource('return-product', ReturnProductController::class)->except(['create','edit']);

    Route::resource('cashier', CashierController::class)->except(['create','edit']);

    Route::resource('supplier', SupplierController::class)->except(['create','edit']);

    Route::resource('owner', OwnerController::class)->except(['create','edit']);

    Route::resource('store', StoreController::class)->only(['show','update']);

    Route::get('report', [ReportController::class, 'report'])->name('report');

    Route::resource('log-activity', LogActivityController::class)->only(['index','destroy']);
});

app/Http/Controllers/CashierController.php
<?php

namespace App\Http\Controllers;

use App\Models\Store;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CashierController extends Controller {
    
    function index() {
        if (request()->ajax()) {
            if (auth()->guard('admin')->check())
                $data = User::with('store')->where(User::ROLE, User::ROLE_CASHIER)->get();
            else 
                $data = User::with('store')->where(User::ROLE, User::ROLE_CASHIER)->where(User::STORE_ID, auth()->user()->store_id)->get();

            return response(['data' => $data]);
        };
        if (auth()->guard('admin')->check())
            $stores = Store::get();
        else
            $stores = auth()->user()->store;
        
        return view('page.cashier.index', compact('stores'));
    }

    function store(Request $request) {
        $validator = Validator::make($request->all(), [
            User::USERNAME => 'required|alpha_dash|unique:users',
            User::FULLNAME => 'required|string',
            User::PASSWORD => 'required|confirmed|min:6',
            User::RELIGION => 'required',
            User::STORE_ID => 'required',
            User::PLACE_BIRTH => 'required',
            User::DATE_BIRTH => 'required',
            User::STORE_ID => 'required|numeric'
        ]);

        if ($validator->fails()) 
            return response(['status' => false, 'error' => $validator->errors()]);

        $payload = $request->all();
        $payload[User::PASSWORD] = bcrypt($payload[User::PASSWORD]);
        $payload[User::ROLE] = User::ROLE_CASHIER;
        User::create($payload);

        session()->flash('status', 'Akun Kasir');
        session()->flash('message', 'baru berhasil tersimpan');

        return response(['status' => true]); 
    }

    function show(User $cashier) {
        $stores = Store::get();

        return view('page.cashier.detail', compact('cashier','stores'));
    }

    function update(Request $request, User $cashier) {
        $payload = $request->except(User::PASSWORD, 'password_confirmation');

        $rules = [
            User::USERNAME => 'required|alpha_dash|unique:users,username,'.$cashier->id,
            User::FULLNAME => 'required|string',
            User::RELIGION => 'required',
            User::PLACE_BIRTH => 'required',
            User::DATE_BIRTH => 'required'
        ];
        
        if ($request->filled('password')) {
            $rules[User::PASSWORD] = 'required|confirmed|min:6';
            $payload[User::PASSWORD] = bcrypt($payload[User::PASSWORD]);
        }

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails())
            return response(['status' => false,'error' => $validator->errors()]);

        $cashier->update($payload);

        session()->flash('status', 'Akun Kasir');
        session()->flash('message', 'berhasil diperbarui');

        return response(['status' => true]);
    }

    function destroy(User $cashier) {
        $cashier->delete();

        return redirect()->back()->with(['status' => 'Akun Kasir', 'message' => 'berhasil terhapus']);
    }
}

resources/views/page/cashier/detail.blade.php
@extends('layout.main')

@section('title', 'Detail Kasir')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <form id="form-cashier">
                    <div class="card-body pb-1">
                        @csrf
                        <input type="hidden" name="_method" value="PUT">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Username</label>
                                    <input type="text" name="username" class="form-control" required value="{{ $cashier->username }}">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Nama Lengkap</label>
                                    <input type="text" name="fullname" class="form-control" required value="{{ $cashier->fullname }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control" name="password" placeholder="-- kosongi jika tidak ingin mengubah password --">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Konfirmasi Password</label>
                                    <input type="password" class="form-control" name="password_confirmation" placeholder="-- kosongi jika tidak ingin mengubah password --">
                                </div>
                            </div>
                        </div>
                        
                    <div class="form-group mb-3">
                        <label>Jenis Kelamin</label>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-check">
                                    <input class="form-check-input" value="Pria" type="radio" name="gender" id="radio-gender-men" {{ $cashier->gender == 'Pria' ? 'checked' : '' }}> 
                                    <label class="form-check-label" for="radio-gender-men">
                                        Pria
                                    </label>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-check">
                                    <input class="form-check-input" value="Wanita" type="radio" name="gender" id="radio-gender-women" {{ $cashier->gender == 'Wanita' ? 'checked' : '' }}>
                                    <label class="form-check-label" for="radio-gender-women">
                                        Wanita
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label>Tempat Lahir</label>
                                <input type="text" class="form-control" name="place_birth" required value="{{ $cashier->place_birth }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label>Tempat Lahir</label>
                                <input type="date" class="form-control" name="date_birth" required value="{{ $cashier->date_birth }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label>Agama</label>
                                <input type="text" class="form-control" name="religion" required value="{{ $cashier->religion }}">
                            </div>
                        </div>
                        <div class="col-6">
                            <label>Nama Toko</label>
                            <select name="store_id" class="form-control">
                                @foreach ($stores as $store)
                                    <option value="{{ $store->id }}" {{ $cashier->store_id == $store->id ? 'selected' : '' }}>{{ $store->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    </div>
                    <div class="card-footer pt-0">
                        <button class="btn btn-primary" id="btn-update-user"><i class="fas fa-plus"></i> Simpan Data Kasir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@endsection

@push('addons-script')
<script>
    $('#btn-update-user').click(function (e) { 
        e.preventDefault();
        clearError('form-cashier');
        let btn = $(this);

        $.ajax({
            type: "post",
            url: "{{ route('cashier.update', $cashier->id) }}",
            data: $('#form-cashier').serialize(),
            dataType: "json",
            beforeSend : function () {
                btn.addClass('btn-progress');
            },
            success: function (response) {
                if (response.status) {
                    window.location.href = "{{ route('cashier.index')}}";
                } else {
                    for (let key of Object.keys(response.error)) {
                        $('[name="'+key+'"]').addClass('is-invalid');
                        $('[name="'+key+'"]').after('<div class="invalid-feedback">'+response.error[key]+'.</div>');
                    }
                    alert('Something wrong !!!');
                    btn.removeClass('btn-progress');
                }
            },
            error: function(xhr, status, error) {
                btn.removeClass('btn-progress');
                console.log(xhr.responseText);
            }
        });
    });
</script>
@endpush

resources/views/page/cashier/index.blade.php
@extends('layout.main')

@section('title', 'Manajemen Akun Kasir')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive" >
                        <table class="table table-striped" id="table-cashier" style="width: 100%">
                            <thead>
                                <tr>
                                    <th class="text-center">No.</th>
                                    <th>Email</th>
                                    <th>Nama Lengkap</th>
                                    <th>Jenis Kelamin</th>
                                    <th>TTL</th>
                                    <th>Agama</th>
                                    <th>Toko</th>
                                    <th class="text-center">Created At</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal Add Cashier-->
<div class="modal fade" id="modal-add-cashier" tabindex="-1" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Tambah Kasir Baru</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <form class="mt-3" id="form-cashier">
                <div class="modal-body">
                    @csrf
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control" name="username" required>
                                <div class="invalid-feedback"></div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label>Nama Lengkap</label>
                                <input type="text" class="form-control" name="fullname" required>
                                <div class="invalid-feedback"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" name="password" required>
                                <div class="invalid-feedback"></div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label>Konfirmasi Password</label>
                                <input type="password" class="form-control" name="password_confirmation" required>
                                <div class="invalid-feedback"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-3">
                        <label>Jenis Kelamin</label>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-check">
                                    <input class="form-check-input" value="Pria" type="radio" name="gender" id="radio-gender-men" checked> 
                                    <label class="form-check-label" for="radio-gender-men">
                                        Pria
                                    </label>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-check">
                                    <input class="form-check-input" value="Wanita" type="radio" name="gender" id="radio-gender-women" >
                                    <label class="form-check-label" for="radio-gender-women">
                                        Wanita
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label>Tempat Lahir</label>
                                <input type="text" class="form-control" name="place_birth" required>
                                <div class="invalid-feedback"></div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label>Tempat Lahir</label>
                                <input type="date" class="form-control" name="date_birth" required>
                                <div class="invalid-feedback"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label>Agama</label>
                                <input type="text" class="form-control" name="religion" required>
                                <div class="invalid-feedback"></div>
                            </div>
                        </div>
                        <div class="col-6">
                            <label>Nama Toko</label>
                            @auth('admin')
                                <select name="store_id" class="form-control">
                                    @foreach ($stores as $store)
                                        <option value="{{ $store->id }}">{{ $store->name }}</option>
                                    @endforeach
                                </select>
                            @else
                                <input type="hidden" class="form-control" name="store_id" value="{{ $stores->id }}">
                                <input type="text" class="form-control" value="{{ $stores->name }}" disabled>
                            @endauth
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="btn-add-user">Tambah</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Delete -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <form action="{{ route('cashier.destroy',1) }}" method="POST" id="form-delete">
                @csrf
                <input type="hidden" name="_method" value="DELETE">
                <div class="modal-body">
                    Apakah anda yakin ingin menghapus akun kasir ini ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Hapus</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('addons-style')
<link rel="stylesheet" href="{{ asset('assets/bundles/datatables/datatables.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
@endpush

@push('addons-script')
<!-- JS Libraies -->
<script src="{{ asset('assets/bundles/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
<!-- Page Specific JS File -->
<script src="{{ asset('assets/js/page/datatables.js') }}"></script>
<script>
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {'X-CSRF-TOKEN': "{{ csrf_token() }}"}
        })
        
        let t = $('#table-cashier').DataTable( {
            "processing": true,
            "ajax": "{!! url()->current() !!}",
            "columns": [
                {
                    "data": null,
                    "width": "10px",
                    "sClass": "text-center",
                    "bSortable": false
                },
                { "data": "username"},
                { "data": "fullname"},
                { "data": "gender", "sClass": "text-center" },
                { "data": "null", "sClass": "text-center", render: function ( data, type, row ) {
                        return row.place_birth+', '+row.date_birth
                    }
                },
                { "data": "religion", "sClass": "text-center" },
                { "data": "store.name"},
                { "data": "created_at", "sClass": "text-center" },
                { "data": "null", "sClass": "text-center", render: function ( data, type, row ) {
                        let url_detail = "{{ route('cashier.show', ':id') }}";
                        return `
                            <a href="`+url_detail.replace(':id', row.id)+`" class="btn btn-sm btn-warning" title="detail"><i class="fas fa-pencil-alt"></i> Detail</a>
                            <button class="btn btn-sm btn-danger" onclick="deletecashier(`+row.id+`)"><i class="fa fa-trash"></i> Hapus</button>
                            `;
                    },"bSortable": false
                }
            ],
            'initComplete': function(){
                $("#table-cashier_length").parent().before(`
                    <div class="col-12 col-md-4 text-center text-md-left">
                        <button class="btn btn-rounded btn-success mb-2" data-toggle="modal" data-target="#modal-add-cashier"><i class="fa fa-plus mr-2"></i> Tambah Kasir</button>
                    </div>
                `);
                $("#table-cashier_length").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6');
                $("#table-cashier_length").css('text-align', 'center');
                $("#table-cashier_filter").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6');
            }   
        });
        t.on( 'order.dt search.dt', function () {
            t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();
    });

    function deletecashier(id) {
        let url_delete = "{{ route('cashier.destroy', ':id') }}";
        $('#form-delete').attr('action', url_delete.replace(':id', id));
        $('#modal-delete').modal('show');
    }

    $('#btn-add-user').click(function (e) { 
        e.preventDefault();
        clearError('form-cashier');
        let btn = $(this);

        $.ajax({
            type: "post",
            url: "{{ route('cashier.store') }}",
            data: $('#form-cashier').serialize(),
            dataType: "json",
            beforeSend : function () {
                btn.addClass('btn-progress');
            },
            success: function (response) {
                if (response.status) {
                    location.reload();
                } else {
                    for (let key of Object.keys(response.error)) {
                        $('[name="'+key+'"]').addClass('is-invalid');
                        $('[name="'+key+'"]').after('<div class="invalid-feedback">'+response.error[key]+'.</div>');
                    }
                    showAlert('Error', 'Silakan periksa formulir', 'Kasir')
                    btn.removeClass('btn-progress');
                }
            },
            error: function(xhr, status, error) {
                btn.removeClass('btn-progress');
                showAlert('Error', 'Terjadi Kesalahan', 'Kasir')
                console.log(xhr.responseText);
            }
        });
    });
</script>
@endpush