routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CashierController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LogActivityController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductPriceController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\PurchaseImageController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReturnProductController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransactionController;

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login'])->name('login.store');
Route::post('logout', [LoginController::class, 'logout'])->middleware('auth:admin,owner,cashier')->name('logout');
    
Route::group(['middleware' => 'auth:admin,owner,cashier'], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('home');

    Route::resource('category', CategoryController::class)->except(['edit','create']);

    Route::resource('product', ProductController::class)->except(['edit']);
    Route::get('product-others', [ProductController::class, 'others'])->name('product.others');
    Route::post('product-import', [ProductController::class, 'import'])->name('product.import');
    Route::resource('product-price', ProductPriceController::class)->only(['store', 'destroy']);
    
    Route::resource('sale', SaleController::class)->except(['edit']);
    Route::resource('transaction', TransactionController::class)->except(['index','edit']);
    Route::get('sale-trash', [SaleController::class, 'trash'])->name('sale.trash');
    
    Route::resource('purchase', PurchaseController::class)->except(['edit']);
    Route::resource('purchase-image', PurchaseImageController::class)->only(['store', 'destroy']);
    
    Route::resource('return-product', ReturnProductController::class)->except(['create','edit']);

    Route::resource('cashier', CashierController::class)->except(['create','edit']);

    Route::resource('supplier', SupplierController::class)->except(['create','edit']);

    Route::resource('owner', OwnerController::class)->except(['create','edit']);

    Route::resource('store', StoreController::class)->only(['show','update']);

    Route::get('report', [ReportController::class, 'report'])->name('report');

    Route::resource('log-activity', LogActivityController::class)->only(['index','destroy']);
});

resources/views/includes/script.blade.php
<!-- General JS Scripts -->
<script src="{{ asset('assets/js/app.min.js') }}"></script>
<!-- JS Libraies -->
<!-- Page Specific JS File -->
<!-- Template JS File -->
<script src="{{ asset('assets/js/scripts.js') }}"></script>
<!-- Custom JS File -->
<script src="{{ asset('assets/js/custom.js') }}"></script>
<script src="{{ asset('assets/bundles/izitoast/js/iziToast.min.js') }}"></script>

<script>
    setTimeout(() => {
        if( $('#notifications-state > *').length > 0 ) {
            let el = $('#notifications-state :first-child');
            let status = el.attr("data-status");
            let message = el.attr("data-message");
            
            if (status != 'error')
                showAlert('success', message, status);
            else 
                showAlert('error', message, 'error');
        }
    }, 500);

    function showAlert(status, message, title) {
        $data = {
            title: title,
            message: message,
            position: 'topRight'
        }

        if (status == 'success')
            iziToast.success($data)
        else 
            iziToast.error($data)
    }

    const formatRupiah = (money) => {
        return new Intl.NumberFormat('id-ID',
            { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }
        ).format(money);
    }

    const popupCenter = ({url, title, w, h}) => {
        // Fixes dual-screen position                             Most browsers      Firefox
        const dualScreenLeft = window.screenLeft !==  undefined ? window.screenLeft : window.screenX;
        const dualScreenTop = window.screenTop !==  undefined   ? window.screenTop  : window.screenY;

        const width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
        const height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

        const systemZoom = width / window.screen.availWidth;
        const left = (width - w) / 2 / systemZoom + dualScreenLeft
        const top = (height - h) / 2 / systemZoom + dualScreenTop
        const newWindow = window.open(url, title, 
        `
        scrollbars=yes,
        width=${w / systemZoom}, 
        height=${h / systemZoom}, 
        top=${top}, 
        left=${left}
        `
        )

        if (window.focus) newWindow.focus();
    }

    $('.main-content').on('click', 'button', function () { 
        $('form').find('.is-invalid').removeClass('is-invalid');
        $('form').find('.is-invalid').next().html('');
    })

    function clearForm() {
        $('form input:not([name=_token],[name=_method])').val('')
        $('form textarea').val('')
        $("form select").val($("form select option:first").val());
    }
</script>

resources/views/includes/sidebar.blade.php
<li class="menu-header">Data Menu</li>

<li class="dropdown {{ request()->is('/') ? 'active' : '' }}">
    <a href="{{ route('home') }}" class="nav-link"><i data-feather="monitor"></i><span>Dashboard Harian</span></a>
</li>

<li class="dropdown {{ request()->is('category*') ? 'active' : '' }}">
    <a href="{{ route('category.index') }}" class="nav-link"><i data-feather="calendar"></i><span>Kategori Produk</span></a>
</li>

@guest('cashier')
    <li class="dropdown {{ request()->is('product*') ? 'active' : '' }}">
        <a href="#" class="menu-toggle nav-link has-dropdown">
            <i data-feather="grid"></i>
            <span>Produk</span>
        </a>
        <ul class="dropdown-menu"> 
            <li class="{{ request()->is('product*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('product.index') }}">Produk Saya</a>
            </li>
            <li class="{{ request()->is('product-others') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('product.others') }}">Produk Toko Lain</a>
            </li>
        </ul>
    </li>
@endguest

@auth('cashier')
    <li class="dropdown {{ request()->is('product*') ? 'active' : '' }}">
        <a href="{{ route('product.index') }}" class="nav-link"><i data-feather="grid"></i><span>Produk</span></a>
    </li>
@endauth

<li class="dropdown {{ request()->is('transaction/create') ? 'active' : '' }}">
    <a href="{{ route('transaction.create') }}" class="nav-link"><i data-feather="shopping-bag"></i><span>Transaksi Baru</span></a>
</li>

<li class="dropdown {{ request()->is('sale/create') ? '' : (request()->is('sale*') ? 'active' : '') }}">
    <a href="{{ route('sale.index') }}" class="nav-link"><i data-feather="shopping-bag"></i><span>Riwayat Transaksi</span></a>
</li>

@guest('cashier')
<li class="dropdown {{ request()->is('purchase*') ? 'active' : '' }}">
    <a href="{{ route('purchase.index') }}" class="nav-link"><i data-feather="shopping-cart"></i><span>Pembelian Produk</span></a>
</li>

<li class="dropdown {{ request()->is('return-product*') ? 'active' : '' }}">
    <a href="{{ route('return-product.index') }}" class="nav-link"><i data-feather="rotate-ccw"></i><span>Pengembalian Produk</span></a>
</li>

<li class="menu-header">Data Master</li>

<li class="dropdown {{ request()->is('cashier*') || request()->is('owner*') || request()->is('supplier*') || request()->is('store*') ? 'active' : '' }}">
    <a href="#" class="menu-toggle nav-link has-dropdown">
        <i data-feather="users"></i>
        <span>Manajemen User</span>
    </a>
    <ul class="dropdown-menu">
        <li class="{{ request()->is('cashier*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('cashier.index') }}">Akun Kasir</a>
        </li>
        @auth('admin')
        <li class="{{ request()->is('owner*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('owner.index') }}">Akun Pemilik</a>
        </li>
        @else 
        <li class="{{ request()->is('owner*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('owner.store', auth()->id()) }}">Akun Saya</a>
        </li>
        @endauth
        <li class="{{ request()->is('supplier*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('supplier.index') }}">Data Supplier</a>
        </li>
        @auth('owner')
        <li class="{{ request()->is('store*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('store.show', auth()->user()->store_id) }}">Toko Saya</a>
        </li>
        @endauth
    </ul>
</li>

<li class="dropdown {{ request()->is('report*') ? 'active' : '' }}">
    <a href="{{ route('report') }}" class="nav-link"><i data-feather="clipboard"></i><span>Laporan</span></a>
</li>

<li class="dropdown {{ request()->is('log*') ? 'active' : '' }}">
    <a href="{{ route('log-activity.index') }}" class="nav-link"><i data-feather="file-text"></i><span>Lihat Aktifitas</span></a>
</li>
@endguest

resources/views/includes/style.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="{{ asset('assets/css/app.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/bundles/izitoast/css/iziToast.min.css') }}">
<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
<!-- Custom style CSS -->
<link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">
<link rel='shortcut icon' type='image/x-icon' href="{{ asset('assets/img/favicon.ico') }}" />