routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CashierController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LogActivityController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductPriceController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\PurchaseImageController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReturnProductController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransactionController;

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login'])->name('login.store');
Route::post('logout', [LoginController::class, 'logout'])->middleware('auth:admin,owner,cashier')->name('logout');
    
Route::group(['middleware' => 'auth:admin,owner,cashier'], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('home');

    Route::resource('category', CategoryController::class)->except(['edit','create']);

    Route::resource('product', ProductController::class)->except(['edit']);
    Route::get('product-others', [ProductController::class, 'others'])->name('product.others');
    Route::post('product-import', [ProductController::class, 'import'])->name('product.import');
    Route::resource('product-price', ProductPriceController::class)->only(['store', 'destroy']);
    
    Route::resource('sale', SaleController::class)->except(['edit']);
    Route::resource('transaction', TransactionController::class)->except(['index','edit']);
    Route::get('sale-trash', [SaleController::class, 'trash'])->name('sale.trash');
    
    Route::resource('purchase', PurchaseController::class)->except(['edit']);
    Route::resource('purchase-image', PurchaseImageController::class)->only(['store', 'destroy']);
    
    Route::resource('return-product', ReturnProductController::class)->except(['create','edit']);

    Route::resource('cashier', CashierController::class)->except(['create','edit']);

    Route::resource('supplier', SupplierController::class)->except(['create','edit']);

    Route::resource('owner', OwnerController::class)->except(['create','edit']);

    Route::resource('store', StoreController::class)->only(['show','update']);

    Route::get('report', [ReportController::class, 'report'])->name('report');

    Route::resource('log-activity', LogActivityController::class)->only(['index','destroy']);
});

app/Models/ReturnProduct.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReturnProduct extends Model {

    use HasFactory;

    const ID = '';
    const USER_ID = 'user_id';
    const PRODUCT_ID = 'product_id';
    const NAME = 'name';
    const CODE = 'code';
    const QTY = 'qty';
    const STATUS = 'status';
    const NOTE = 'note';

    protected $guarded = [];

    protected $casts = [
        Self::CREATED_AT => 'datetime:Y-m-d H:i:s',
        Self::UPDATED_AT => 'datetime:Y-m-d H:i:s'
    ];

    function user() {
        return $this->belongsTo(User::class);
    }

    function product() {
        return $this->belongsTo(Product::class);
    }

}

app/Http/Controllers/ReturnProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ReturnProduct;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ReturnProductController extends Controller {

    public function index() {
        if (request()->ajax()) {
            if (auth()->guard('admin')->check()) 
                $data = ReturnProduct::with('user','product')->get();
            else 
                $data = ReturnProduct::with('user','product')->whereHas('user', function($q) {
                    $q->where(ReturnProduct::USER_ID, auth()->id());
                })->get();

            return response(['data' => $data]);
        }
        $products = Product::get();
        return view('page.return-product.index', compact('products'));
    }

    public function store(Request $request) {
        $credentials = $request->all();

        DB::beginTransaction();

        try {
            $product = Product::find($credentials[ReturnProduct::PRODUCT_ID]);
            $product->decrementStok($request->input(ReturnProduct::QTY));

            $credentials[ReturnProduct::NAME] = $product->name;
            $credentials[ReturnProduct::CODE] = $product->code;
    
            ReturnProduct::create($credentials);
    
            DB::commit();
            return redirect()->back()->with(['status' => 'Pengembalian Produk', 'message' => 'data berhasil tersimpan']);
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->back()->with(['status' => 'error', 'message' => $th->getMessage()]);
        }
    }

    public function show(ReturnProduct $returnProduct) {
        return view('page.return-product.detail', compact('returnProduct'));
    }

    public function update(Request $request, ReturnProduct $returnProduct) {
        $payload = $request->all();

        DB::beginTransaction();

        try {
            if ($payload[ReturnProduct::PRODUCT_ID] != 0) {
                $product = Product::find($payload[ReturnProduct::PRODUCT_ID]);
                if ($returnProduct->qty != $payload[ReturnProduct::QTY]) {
                    $qty = $payload[ReturnProduct::QTY] - $returnProduct->qty;
                    $product->decrementStok($qty);
                }
            }

            $returnProduct->update($payload);
    
            DB::commit();
            return redirect()->route('return-product.index')->with(['status' => 'Pengembalian Produk', 'message' => 'data berhasil tersimpan']);
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('return-product.index')->with(['status' => 'error', 'message' => $th->getMessage()]);
        }
    }

    public function destroy(ReturnProduct $returnProduct) {
        DB::beginTransaction();

        try {
            if ($returnProduct[ReturnProduct::PRODUCT_ID] != 0) {
                $product = Product::find($returnProduct->product_id);
                $product->incrementStok($returnProduct->qty);
            }
            $returnProduct->delete();
            
            DB::commit();
            return redirect()->back()->with(['status' => 'Pengembalian Produk', 'message' => 'data berhasil terhapus']);
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->back()->with(['status' => 'error', 'message' => $th->getMessage()]);
        }
    }
}

resources/views/page/return-product/detail.blade.php
@extends('layout.main')

@section('title', 'Detail Pengembalian Produk')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <form action="{{ route('return-product.update', $returnProduct->id) }}" id="form-product" method="POST">
                    <input type="hidden" name="_method" value="PUT" />
                    <input type="hidden" name="product_id" value="{{ $returnProduct->product_id }}">
                    <div class="card-body pb-1">
                        @csrf
                        <div class="form-group">
                            <label>Nama Product</label>
                            <input type="text" class="form-control" name="name" required value="{{ $returnProduct->name }}">
                        </div>
                        <div class="form-group">
                            <label>Kode</label>
                            <input type="text" class="form-control" name="code" required value="{{ $returnProduct->code }}">
                        </div>
                        <div class="form-group">
                            <label>Banyak Barang</label>
                            <input type="text" class="form-control" name="qty" required value="{{ $returnProduct->qty }}">
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <select name="status" class="form-control">
                                <option value="pending" {{ $returnProduct->status == 'pending' ? 'selected' : '' }}>Pending</option>
                                <option value="succeed" {{ $returnProduct->status == 'succeed' ? 'selected' : '' }}>Succeed</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Note.</label>
                            <textarea name="note" rows="5" class="form-control" style="height: auto !important">{{ $returnProduct->note }}</textarea>
                        </div>
                    </div>
                    <div class="card-footer pt-0">
                        <button class="btn btn-primary" type="submit"><i class="fas fa-pencil-alt"></i> Simpan Perubahan Data</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/page/return-product/index.blade.php
@extends('layout.main')

@section('title', 'Daftar Pengembalian Produk')

@section('content')
<section class="section">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive" >
                        <table class="table table-striped" id="table-product" style="width: 100%">
                            <thead>
                                <tr>
                                    <th class="text-center">No.</th>
                                    <th>Nama</th>
                                    <th>Kode</th>
                                    <th class="text-center">Amount</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Created At</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal Add Product-->
<div class="modal fade" id="modal-add-return" tabindex="-1" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Form Pengembalian Barang</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <form class="mt-3" method="POST" action="{{ route('return-product.store') }}" >
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="user_id" value="{{ auth()->id() }}">
                    <div class="form-group">
                        <label>Produk yang dikembalikan</label>
                        <select name="product_id" class="form-control">
                            @foreach ($products as $product)
                                <option value="{{ $product->id }}">{{ $product->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Banyak Barang</label>
                        <input type="number" class="form-control" name="qty">
                    </div>
                    <div class="form-group">
                        <label>Note.</label>
                        <textarea name="note" rows="5" class="form-control" placeholder="catatan pengembalian produk"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Tambah</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Konfirmasi Hapus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <form action="{{ route('return-product.destroy',1) }}" method="POST" id="form-delete">
                @csrf
                <input type="hidden" name="_method" value="DELETE" />
                <div class="modal-body">
                    Apakah anda yakin ingin menghapus data pengembalian barang ini ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Hapus</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('addons-style')
<link rel="stylesheet" href="assets/bundles/datatables/datatables.min.css">
<link rel="stylesheet" href="assets/bundles/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css">
@endpush

@push('addons-script')
<!-- JS Libraies -->
<script src="assets/bundles/datatables/datatables.min.js"></script>
<script src="assets/bundles/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="assets/bundles/jquery-ui/jquery-ui.min.js"></script>
<!-- Page Specific JS File -->
<script src="assets/js/page/datatables.js"></script>
<script>
    $(document).ready(function () {
        let t = $('#table-product').DataTable( {
            "processing": true,
            "ajax": "{!! url()->current() !!}",
            "columns": [
                {
                    "data": null,
                    "width": "10px",
                    "sClass": "text-center",
                    "bSortable": false
                },
                { "data": "name"},
                { "data": "code"},
                { "data": "qty", "sClass": "text-center"},
                { "data": "null", "sClass": "text-center", render: function ( data, type, row ) {
                        if (row.status == 'pending')
                            return `<label class="badge badge-warning">Pending</label>`; 
                        else
                            return `<label class="badge badge-success">Succeed</label>`; 
                    }
                },
                { "data": "created_at", "sClass": "text-center" },
                { "data": "null", "sClass": "text-center", render: function ( data, type, row ) {
                        let url_detail = "{{ route('return-product.show', ':id') }}";
                        return `
                            <a href="`+url_detail.replace(':id', row.id)+`" class="btn btn-warning" title="detail"><i class="fas fa-pencil-alt"></i> Detail</a>
                            <button class="btn btn-danger" onclick="deleteProduct(`+row.id+`)"><i class="fa fa-trash"></i> Hapus</button>
                            `;
                    },"bSortable": false
                }
            ],
            'initComplete': function(){
                $("#table-product_length").parent().before(`
                    <div class="col-12 col-md-4 text-center text-md-left">
                        <button class="btn btn-rounded btn-success mb-2" type="button" data-toggle="modal" data-target="#modal-add-return"><i class="fa fa-plus"></i> Tambahkan Pengembalian</button>
                    </div>
                `);
                $("#table-product_length").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
                $("#table-product_length").css('text-align', 'center');
                $("#table-product_filter").parent().addClass('col-12 col-sm-6 col-md-4').removeClass('col-sm-12 col-md-6')
            }   
        });
        t.on( 'order.dt search.dt', function () {
            t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();
    });

    function deleteProduct(id) {
        let url_delete = "{{ route('return-product.destroy', ':id') }}";
        $('#form-delete').attr('action', url_delete.replace(':id', id));
        $('#modal-delete').modal('show');
    }
</script>
@endpush